### PR TITLE
[fix] now sort the items of active project's combobox; also sort the combobox items and projects tree on project name change event

### PR DESCRIPTION
**Pull request by nandishjpatel**

### CODE REVIEW

**Comment by tepals** [comment]
could you explain what this does? Maybe with a picture?

**Comment by nandishjpatel** [comment]
> could you explain what this does? Maybe with a picture?

Previously
image

Now
image

Also the sort order in `Active project` combobox is maintained
Screenshot from 2024-11-26 10-37-01

**Comment by tepals** [comment]
and since you are using sorted if you have the list `"BM_1", "BM_3", "BM_10"` it will get sorted as `"BM_1", "BM_10", "BM_3"`, right?

**Comment by nandishjpatel** [comment]
> and since you are using sorted if you have the list `"BM_1", "BM_3", "BM_10"` it will get sorted as `"BM_1", "BM_10", "BM_3"`, right?

Right

**Review by K4rishma — APPROVED** [review]

**Review by tepals — APPROVED** [review]

**Pull request merged**
