### PR TITLE
debian-control: add wxgtk3 dependency

### PR DESCRIPTION
**Pull request by philipwinklerdelmic**

### CODE REVIEW

**Comment by philipwinklerdelmic** [comment]
Actually, there was an issue on ubuntu 18.04. We need to install this extra dependency for wx to work.

**Comment by pieleric** [comment]
Can you explain more the issue? It sounds like an horrible dependency. What is missing in wxgtk4? Wxversion ?

**Comment by philipwinklerdelmic** [comment]
Sorry, I forgot again about this pythonpath issue. Actually, it works with wxgtk4, but we have to add `/usr/lib/python2.7/dist-packages/wxPython-4.0.1-py2.7-linux-amd64.egg` to the pythonpath. I can add this to bashrc in the ubuntu-delmic install script.

**Comment by philipwinklerdelmic** [comment]
I pushed some changes to ubuntu-delmic. Could you have a look?

**Pull request closed without merging**
