### PR TITLE
Updating the scanOffset and scanGain default values

### PR DESCRIPTION
**Pull request by Kleijwegt**

### CODE REVIEW

**Review by pieleric — COMMENTED** [review]
How "stable" are these values going to be? If that's the typical values for all the FAST-EMs, why not. Otherwise, I'd suggest to leave basic values (maybe 0.1 for the scanGain?), and use the microscope file to have default "better" values. You can do it by adding a section to the component that looks like:
```
properties: {
    scanOffset: [0.1172, 0.0989],
    :
}
```

**Comment by Kleijwegt** [comment]
Approved number by Wilco Zuidema

**Comment by pieleric** [comment]
My question is more: have these numbers any chance to stay approved for the rest of the FASTEMs, or they only make sense (with such precision) on the first/test system?

**Comment by Kleijwegt** [comment]
I have set easier default values.
I will make a PR on bitbucket for the precise values in the yaml file

**Review by Sabrina85 — APPROVED** [review]

**Pull request merged**
