### PR TITLE
[FEAT]: convert shapes list to va

### PR DESCRIPTION
**Pull request by patrickcleeve2**
Convert the _shapes list to a VA, allowing it to be subscribed to for when shapes are removed. Used for milling patterns

### CODE REVIEW

**Review by pieleric — COMMENTED** [review]
You're only providing one "side" of the changes. It shows how the current code is changed, but not what you use these changes for. So it's a bit hard to be review how helpful this change is.
That said, I would not recommend changing a private attribute to a VA in order to be able to observe it, because it's "private". You could make it "public". However, in this case, I think it would make more sense to have the VA on the model (ie, one of the classes in gui.model), and pass this VA to the overlay, at creation. Then the overlay can update/observe the VA based on user inputs. I think it would make sense to also have "selected_shape" also a VA on the model.

**Comment by patrickcleeve2** [comment]
> You're only providing one "side" of the changes. It shows how the current code is changed, but not what you use these changes for. So it's a bit hard to be review how helpful this change is. That said, I would not recommend changing a private attribute to a VA in order to be able to observe it, because it's "private". You could make it "public". However, in this case, I think it would make more sense to have the VA on the model (ie, one of the classes in gui.model), and pass this VA to the overlay, at creation. Then the overlay can update/observe the VA based on user inputs. I think it would make sense to also have "selected_shape" also a VA on the model.

Context for change is in: https://github.com/delmic/odemis/pull/2754. Basically, there is currently no-way of knowing when shapes are removed by the user. There is already a specific VA for new_shape, so you can know when they are created. 

I agree this can probably be 'public'. I don't think it makes sense to move the va to the models, the shapes are properties of the overlays, and only ui elements.  They are only used for display of some other internal state (patterns for meteor, roa for fastem).

**Comment by nandishjpatel** [comment]
> > You're only providing one "side" of the changes. It shows how the current code is changed, but not what you use these changes for. So it's a bit hard to be review how helpful this change is. That said, I would not recommend changing a private attribute to a VA in order to be able to observe it, because it's "private". You could make it "public". However, in this case, I think it would make more sense to have the VA on the model (ie, one of the classes in gui.model), and pass this VA to the overlay, at creation. Then the overlay can update/observe the VA based on user inputs. I think it would make sense to also have "selected_shape" also a VA on the model.
> 
> Context for change is in: #2754. Basically, there is currently no-way of knowing when shapes are removed by the user. There is already a specific VA for new_shape, so you can know when they are created.
> 
> I agree this can probably be 'public'. I don't think it makes sense to move the va to the models, the shapes are properties of the overlays, and only ui elements. They are only used for display of some other internal state (patterns for meteor, roa for fastem).

I also need the removed functionality in the future :) Using the ListVA do you use some kind of set comparison to find the removed shape @patrickcleeve2 ?

In one of my PR's I am gonna use a named tuple [ShapeState](https://github.com/nandishjpatel/odemis/blob/c13c3e013b352b702cfc46afb78c10f38af57c04/src/odemis/gui/comp/overlay/shapes.py#L36). Do you think this can be the `new_shape` VA value (most probably rename the VA). This named tuple has attributes `is_new`, `is_deleted` . What do you think?

**Comment by patrickcleeve2** [comment]
> > > You're only providing one "side" of the changes. It shows how the current code is changed, but not what you use these changes for. So it's a bit hard to be review how helpful this change is. That said, I would not recommend changing a private attribute to a VA in order to be able to observe it, because it's "private". You could make it "public". However, in this case, I think it would make more sense to have the VA on the model (ie, one of the classes in gui.model), and pass this VA to the overlay, at creation. Then the overlay can update/observe the VA based on user inputs. I think it would make sense to also have "selected_shape" also a VA on the model.
> > 
> > 
> > Context for change is in: #2754. Basically, there is currently no-way of knowing when shapes are removed by the user. There is already a specific VA for new_shape, so you can know when they are created.
> > I agree this can probably be 'public'. I don't think it makes sense to move the va to the models, the shapes are properties of the overlays, and only ui elements. They are only used for display of some other internal state (patterns for meteor, roa for fastem).
> 
> I also need the removed functionality in the future :) Using the ListVA do you use some kind of set comparison to find the removed shape @patrickcleeve2 ?
> 
> In one of my PR's I am gonna use a named tuple [ShapeState](https://github.com/nandishjpatel/odemis/blob/c13c3e013b352b702cfc46afb78c10f38af57c04/src/odemis/gui/comp/overlay/shapes.py#L36). Do you think this can be the `new_shape` VA value (most probably rename the VA). This named tuple has attributes `is_new`, `is_deleted` . What do you think?

@nandishjpatel Yep, I check the list of patterns and find which has been removed. 

I'm having trouble visualising how that va would be used. Does it trigger an event every time you create / delete the shape, and then you implement a check of is_new or is_deleted? Would you be able to show an example?

**Comment by nandishjpatel** [comment]
> > > > You're only providing one "side" of the changes. It shows how the current code is changed, but not what you use these changes for. So it's a bit hard to be review how helpful this change is. That said, I would not recommend changing a private attribute to a VA in order to be able to observe it, because it's "private". You could make it "public". However, in this case, I think it would make more sense to have the VA on the model (ie, one of the classes in gui.model), and pass this VA to the overlay, at creation. Then the overlay can update/observe the VA based on user inputs. I think it would make sense to also have "selected_shape" also a VA on the model.
> > > 
> > > 
> > > Context for change is in: #2754. Basically, there is currently no-way of knowing when shapes are removed by the user. There is already a specific VA for new_shape, so you can know when they are created.
> > > I agree this can probably be 'public'. I don't think it makes sense to move the va to the models, the shapes are properties of the overlays, and only ui elements. They are only used for display of some other internal state (patterns for meteor, roa for fastem).
> > 
> > 
> > I also need the removed functionality in the future :) Using the ListVA do you use some kind of set comparison to find the removed shape @patrickcleeve2 ?
> > In one of my PR's I am gonna use a named tuple [ShapeState](https://github.com/nandishjpatel/odemis/blob/c13c3e013b352b702cfc46afb78c10f38af57c04/src/odemis/gui/comp/overlay/shapes.py#L36). Do you think this can be the `new_shape` VA value (most probably rename the VA). This named tuple has attributes `is_new`, `is_deleted` . What do you think?
> 
> @nandishjpatel Yep, I check the list of patterns and find which has been removed.
> 
> I'm having trouble visualising how that va would be used. Does it trigger an event every time you create / delete the shape, and then you implement a check of is_new or is_deleted? Would you be able to show an example?

Here is an example which you can try:

```
from collections import namedtuple
from enum import Enum

from odemis import model

# Named tuple for elements stored in undo and redo stacks
ShapeState = namedtuple("ShapeState", ["shape", "state", "action"])
# Enum class to store ShapeState's action
Action = Enum("Action", ["EDIT", "CREATE", "DELETE"])

def on_new_shape(shape: ShapeState):
    print(f"{shape.shape} {shape.state} {shape.action}")

new_shape = model.VigilantAttribute(None, readonly=True)
new_shape.subscribe(on_new_shape)

shape = "Rectangle"

new_shape._set_value(ShapeState(shape=shape, state=1, action=Action.CREATE), force_write=True)
new_shape._set_value(ShapeState(shape=shape, state=1, action=Action.EDIT), force_write=True)
new_shape._set_value(ShapeState(shape=shape, state=1, action=Action.DELETE), force_write=True)
new_shape._set_value(ShapeState(shape=shape, state=2, action=Action.EDIT), force_write=True)
```

**Comment by patrickcleeve2** [comment]
> > Context for change is in: #2754. Basically, there is currently no-way of knowing when shapes are removed by the user. There is already a specific VA for new_shape, so you can know when they are created.
> > I agree this can probably be 'public'. I don't think it makes sense to move the va to the models, the shapes are properties of the overlays, and only ui elements. They are only used for display of some other internal state (patterns for meteor, roa for fastem).
> 
> VAs are good for representing states. Using them to indicating events (or changes of the state) is tricky. Especially, in theory, the VA API doesn't promise that every change of value is reported to all subscribers. If the values changes too fast, there _might_ be some intermediary values not reported to the subscribers. In the context of the GUI, for now, I think every value is always reported so that's more just a "long term risk".

But since you can subscribe to the 'state', you get an event when that VA 'state' changes. So for this case, you effectively get an event every time a shape is added/removed. Is that different?

> In my opinion, the shapes that the user draw in the GUI (either for the FASTEM RoAs or the METEOR milling patterns) are part of the GUI state. So _ideally_ the information of the shape should be on the model, as VA(s), and the Overlays would listen/update the VAs according to the user interaction.

I don't really know which model you're referring to, can you give an example? I'm not sure about fastem but for milling patterns, they are also on the milling model (https://github.com/delmic/odemis/blob/57a23d36e323a178c70d45739d60cfe68fbe8a52/src/odemis/gui/comp/milling.py), because they can be changes from shape updates or text/data entries. You'd still need the overlay / shapes themselves to send state updates when they get deleted or added?  

> That's not to say you cannot use VAs in other cases. It's totally fine to use VAs outside of the model, and use them as "communication way" between objects.
> 
> To conclude, I'm fine with making this VA public. However, please also evaluate whether all the information shown by the GUI is in the model. It might be the better answer... I cannot really say until I get a better understanding of the "user" code.

**Comment by nandishjpatel** [comment]
@patrickcleeve2 do you need this feature change right now? I will be finishing my VolumeEM GUI development in a month from now. Can this wait for a while? Also if this change go into master, there will be some merge conflicts.

Given the discussion so far, I think its best to the `shapes` ListVA in the model. I also foresee this suggestion from @pieleric  in my ongoing work.

**Comment by patrickcleeve2** [comment]
Yeah it can wait for a while. In the meantime, I'll just make a different version of the overlay for milling, we can then pick this up when you're done.

**Pull request closed without merging**
