### PR TITLE
python3 migration: andorshrk driver

### PR DESCRIPTION
**Pull request by philipwinklerdelmic**

### CODE REVIEW

**Comment by philipwinklerdelmic** [comment]
should be good now

**Comment by pieleric** [comment]
I think that (almost?) every argument to the library which is instantiated with `create_string_buffer()` should be converted back-and-forth between bytes and (unicode) string on Python 3.
On the simulator side, just initialise the values as bytes, and you don't need to `.encode()` them.

**Comment by philipwinklerdelmic** [comment]
Updated the pull request, but I'm not entirely convinced yet. The test cases always seem to pass, maybe I need to test some more things.

**Comment by philipwinklerdelmic** [comment]
done

**Pull request merged**
