### PR TITLE
add software binning to ueye camera

### PR DESCRIPTION
**Pull request by pieleric**

### CODE REVIEW

**Comment by pieleric** [comment]
The ueye code is untested on the real hardware. It should done before merging this pull-request.

**Review by tepals — APPROVED** [review]
Didn't see anything strange

**Review by Mahmood-B — COMMENTED** [review]
@pieleric  the ueye code is not tested on hardware, but also not on software (unit tests)? I mean there are no testing for the additions in the file of ueye?

**Review by Helsloot — CHANGES_REQUESTED** [review]
I agree with Mahmood's comment about division-by-zero. It would be nice to have that check. Though I'm also wondering how necessary it is to fool proof the inner workings of Odemis like that. On the other hand, adding such a check definitely won't hurt.

**Comment by pieleric** [comment]
> @pieleric the ueye code is not tested on hardware, but also not on software (unit tests)? I mean there are no testing for the additions in the file of ueye?
Actually, the ueye test cases inherit from the "cam_test_abs" which automatically tests binning if the driver provides it. So it should be tested now. That said, there is no uEye simulator, and I had access to the hardware for such a short period that I didn't have time to run the test cases. So there should be test cases, but they haven't been run yet. I'll try to run them next time I have access to such CCD.

**Review by Helsloot — APPROVED** [review]

**Pull request merged**
