### PR TITLE
[ci] updated yaml file to parse the logs

### PR DESCRIPTION
**Pull request by nandishjpatel**
the logs are now generated locally on the ci server

### CODE REVIEW

**Review by pieleric — COMMENTED** [review]
Haven't you removed the part that actually runs the VMs? Or how does this work?
Do the VMs automatically run on the machine, independent of github?

**Review by sneepstefan — APPROVED** [review]

**Comment by nandishjpatel** [comment]
> Haven't you removed the part that actually runs the VMs? Or how does this work? Do the VMs automatically run on the machine, independent of github?

Given we are now running the VMs locally, I reduced the RAM allotment to 16GB for the VMs. The VMs will be fired sequentially and in parallel.

How I do this? I make use of the `cron` service for the triggers. You can check its status by using `systemctl status cron`

How to configure the config file of this cron service? Command: `crontab -e`

The current config file
```
# For more information see the manual pages of crontab(5) and cron(8)
# 
# m h  dom mon dow   command

# ubuntu18        
# on: "0 17 * * 0-4"  # sunday to thursday at 5 pm UTC, for Amsterdam it is +1 UTC during winter and +2 UTC during summer
0 17 * * 0-4 /home/ci/ci/ubuntu18/service/action.sh

# ubuntu20        
# on: "5 17 * * 0-4"  # sunday to thursday at 5:05 pm UTC, for Amsterdam it is +1 UTC during winter and +2 UTC during summer
5 17 * * 0-4 /home/ci/ci/ubuntu20/service/action.sh

# ubuntu22        
# on: "10 17 * * 0-4"  # sunday to thursday at 5:10 pm UTC, for Amsterdam it is +1 UTC during winter and +2 UTC during summer
10 17 * * 0-4 /home/ci/ci/ubuntu22/service/action.sh
```

**Comment by pieleric** [comment]
Thanks Nandish for the detailed explanation. Please make sure this is also in a document about the VMs for testing.

**Comment by nandishjpatel** [comment]
> Thanks Nandish for the detailed explanation. Please make sure this is also in a document about the VMs for testing.

Updated the documentation here: https://docs.google.com/document/d/1YTPWNXT9yHLjhC89muhqfAgzdAl-OXJV/edit#heading=h.7p8j60vbfyzq

**Review by tepals — APPROVED** [review]

**Pull request merged**
