### PR TITLE
fix RuntimeWarning: numpy.ndarray size changed, may indicate binary i…

### PR DESCRIPTION
**Pull request by nandishjpatel**
…ncompatibility by filtering it

### CODE REVIEW

**Review by tepals — APPROVED** [review]

**Review by FCanberk — APPROVED** [review]

**Review by pieleric — APPROVED** [review]
In the commit message, could you indicate how to reproduce this warning? Is it on Ubuntu 18.04? I don't recall seeing it on 20.04... Or does it only happen if a new version of numpy is installed with pip?

**Comment by nandishjpatel** [comment]
> In the commit message, could you indicate how to reproduce this warning? Is it on Ubuntu 18.04? I don't recall seeing it on 20.04... Or does it only happen if a new version of numpy is installed with pip?

It's happening on Ubuntu 20.04 (). It could be because of step no 28. in the odemis testing document (https://docs.google.com/document/d/1pG7fviVLdISrF6BNnnd5kChT09DVfNz_/edit). Do you think this is a proper fix, or we can solve this in a better way?

**Comment by pieleric** [comment]
Yes, that's most likely because a newer version of numpy is installed with pip. As discussed before, that also means that our whole CI runs with a version of numpy that most of the user don't have, just for one feature which is under (slow) development. Now it also causes warnings.
Let's leave this as is, with the code to hide the warning. We should try to find a better solution for the long term...

**Comment by pieleric** [comment]
@nandishjpatel Can you update the commit message with all this info?

**Pull request merged**
